/** Schemas for main-owned tools, advertised by the same registry that executes them. */
const str = { type: "string" };
const bool = { type: "boolean" };
const number = { type: "number" };
const schema = (properties: Record<string, unknown>, required: string[] = []) => ({ type: "object", properties, required, additionalProperties: false });
const target = { browserId: str };
const ref = { ...target, snapshotId: str, ref: str };
const locator = schema({ role: str, name: str, label: str, text: str, placeholder: str, testId: str, css: str, exact: bool, index: { type: "integer", minimum: 0 }, frames: { type: "array", items: str, maxItems: 8 } });
const operation = (values: string[]) => ({ type: "string", enum: values });
export const NEXUS_LOCAL_TOOL_SCHEMAS: Record<string, { description: string; parameters: Record<string, unknown> }> = {
 BrowserPreview: { description: "Open an HTML file inside this session workspace or scratch directory in Nexus Browser with live reload.", parameters: schema({ path: str }, ["path"]) },
 browser_capabilities: { description: "Discover built-in Browser operations, backend support and limits.", parameters: schema({}) },
 browser_tabs: { description: "Create, select, close or mark a chat-owned tab. Creation returns a new exact browserId; navigate that ID separately.", parameters: schema({ ...target, operation: operation(["create", "select", "close", "mark"]), disposition: operation(["temporary", "deliverable", "handoff"]) }, ["operation"]) },
 browser_list_tabs: { description: "List Nexus Browser tabs and their browserId. Does not navigate.", parameters: schema({}) },
 browser_open: { description: "Open or reuse Nexus Browser; supply url to navigate. Return browserId for subsequent calls.", parameters: schema({ url: str }) },
 browser_navigate: { description: "Navigate a specific Nexus Browser tab. Verify the final URL using browser_snapshot.", parameters: schema({ ...target, url: str }, ["browserId", "url"]) },
 browser_snapshot: { description: "Read the bounded accessibility tree. References are scoped to browserId and snapshotId; refresh after navigation.", parameters: schema(target, ["browserId"]) },
 browser_screenshot: { description: "Capture Nexus Browser. Vision-capable models receive the actual image. Full-page captures report truncation; clip uses document CSS pixels.", parameters: schema({ ...target, fullPage: bool, clip: schema({ x: number, y: number, width: number, height: number }, ["x", "y", "width", "height"]), format: operation(["png", "jpeg"]), quality: { type: "integer", minimum: 1, maximum: 100 }, maxWidth: { type: "integer", minimum: 240, maximum: 3840 }, maxHeight: { type: "integer", minimum: 240, maximum: 4096 } }, ["browserId"]) },
 browser_click: { description: "Click a reference from the current snapshot. Never retry an ambiguously applied action without inspecting the page.", parameters: schema({ ...ref, button: operation(["left", "right", "middle"]) }, ["browserId", "snapshotId", "ref"]) },
 browser_fill: { description: "Replace a current snapshot field's text.", parameters: schema({ ...ref, text: str }, ["browserId", "snapshotId", "ref", "text"]) },
 browser_type: { description: "Type text into a current reference or focused element.", parameters: schema({ ...ref, text: str, clearFirst: bool }, ["browserId", "text"]) },
 browser_keypress: { description: "Send a bounded keypress to Nexus Browser.", parameters: schema({ ...ref, key: str, modifiers: { type: "array", items: str } }, ["browserId", "key"]) },
 browser_wait: { description: "Wait for a bounded URL, text, or load condition.", parameters: schema({ ...target, condition: { type: "object", properties: { kind: { type: "string", enum: ["url", "text", "page_load"] }, match: { type: "string", enum: ["equals", "contains"] }, value: str }, required: ["kind"], additionalProperties: false }, timeoutMs: number }, ["browserId", "condition"]) },
 browser_set_viewport: { description: "Set the browser CSS viewport for desktop/mobile verification; reset=true restores panel sizing.", parameters: schema({ ...target, width: { type: "integer", minimum: 240, maximum: 3840 }, height: { type: "integer", minimum: 240, maximum: 2160 }, mobile: bool, reset: bool }, ["browserId"]) },
 browser_console: { description: "Read filtered browser console diagnostics with repeat counts.", parameters: schema({ ...target, limit: number, types: { type: "array", items: str }, contains: str, since: number, clear: bool }, ["browserId"]) },
 browser_evaluate: { description: "Evaluate JavaScript in the explicit browser tab; results are bounded and sanitized.", parameters: schema({ ...target, expression: str }, ["browserId", "expression"]) },
 browser_cdp: { description: "Call baseline CDP or approved site-scoped Developer methods for network/performance/CSS/media diagnostics. Global cookies, storage, target control and interception remain denied.", parameters: schema({ ...target, method: str, params: { type: "object", additionalProperties: true } }, ["browserId", "method"]) },
 browser_interact: { description: "Use Playwright semantic locators and nested frames with strict matching and actionability checks. Inspect/wait are Plan-safe; all mutation actions are Agent-only.", parameters: schema({ ...target, action: operation(["click", "hover", "fill", "type", "press", "check", "select", "drag", "scroll", "mouse", "wait", "inspect"]), locator, destination: locator, text: str, key: str, checked: bool, values: { type: "array", items: str, maxItems: 100 }, button: operation(["left", "right", "middle"]), clickCount: { type: "integer", minimum: 1, maximum: 2 }, deltaX: number, deltaY: number, x: number, y: number, state: operation(["attached", "detached", "visible", "hidden"]), timeoutMs: { type: "integer", minimum: 250, maximum: 8000 } }, ["browserId", "action"]) },
 browser_dialog: { description: "Inspect or respond to a JavaScript dialog in the tab.", parameters: schema({ ...target, operation: operation(["status", "accept", "dismiss"]), text: str }, ["browserId", "operation"]) },
 browser_developer: { description: "Enable Developer diagnostics with explicit user approval for the current site, revoke access or check status.", parameters: schema({ ...target, operation: operation(["status", "enable", "disable"]) }, ["browserId", "operation"]) },
 browser_events: { description: "Read Developer events after a cursor; reports lost history and remaining events.", parameters: schema({ ...target, cursor: { type: "integer", minimum: 0 }, limit: { type: "integer", minimum: 1, maximum: 100 }, methods: { type: "array", items: str } }, ["browserId"]) },
 browser_downloads: { description: "List, pause, resume or cancel tab-owned managed downloads into chat scratch.", parameters: schema({ ...target, operation: operation(["list", "pause", "resume", "cancel"]), id: str }, ["browserId", "operation"]) },
 browser_upload: { description: "Ask the user to choose files for a file-input locator. Only user-selected files can be uploaded.", parameters: schema({ ...target, locator }, ["browserId", "locator"]) },
 browser_page: { description: "Read text/links, inventory assets, save a listed asset or export HTML/text/PDF to chat scratch.", parameters: schema({ ...target, operation: operation(["content", "assets", "save_asset", "export"]), url: str, format: operation(["html", "text", "pdf"]) }, ["browserId", "operation"]) },
 browser_annotations: { description: "Start, read or clear user-selected element annotations with CSS-pixel rectangles.", parameters: schema({ ...target, operation: operation(["start", "read", "clear"]) }, ["browserId", "operation"]) },
 browser_styles: { description: "Apply or clear a temporary bounded style preview; no workspace files are changed.", parameters: schema({ ...target, operation: operation(["apply", "clear"]), selector: str, properties: { type: "object", additionalProperties: str, maxProperties: 30 } }, ["browserId", "operation"]) },
 browser_webmcp: { description: "List document-bound WebMCP tools or call one with user approval and matching documentUrl/documentGeneration. Unsupported documents return supported=false.", parameters: schema({ ...target, operation: operation(["list", "call"]), documentUrl: str, documentGeneration: { type: "integer", minimum: 0 }, name: str, args: { type: "object", additionalProperties: true } }, ["browserId", "operation"]) },
 Skill: { description: "Load a skill document by an id in this session's skill catalog. Guidance grants no permissions.", parameters: schema({ id: str }, ["id"]) },
 Workflow: { description: "Inspect, activate or dismiss a Nexus workflow.", parameters: schema({ operation: { type: "string", enum: ["status", "list", "activate", "dismiss"] }, id: str }, ["operation"]) },
 GitWorktree: { description: "Manage a Nexus-owned worktree in the current project; confirmations remain visible.", parameters: schema({ operation: { type: "string", enum: ["status", "create", "merge", "cleanup"] }, branch: str }, ["operation", "branch"]) },
 PluginScaffold: { description: "Scaffold a Nexus plugin in the specified directory.", parameters: schema({ template: str, directory: str, id: str, name: str }, ["template", "directory"]) },
 PluginCheck: { description: "Validate a local Nexus plugin.", parameters: schema({ directory: str }, ["directory"]) },
 PluginPack: { description: "Package a local Nexus plugin.", parameters: schema({ directory: str }, ["directory"]) },
};
