export type ProviderAccountState = "ready" | "stale" | "unavailable" | "unsupported";
export type ProviderAccountSnapshot = { provider: string; scope: "account"; state: ProviderAccountState; updatedAt?: number; staleAt?: number; plan?: string | null; wallet?: { balanceUsd?: string; heldUsd?: string }; windows?: Array<{ kind: string; remainingUsd?: string; resetsInSec?: number }>; freeTokens?: { usedToday?: number; limitPerDay?: number | null; remaining?: number | null }; error?: string };
export type ProviderAccountHistory = { provider: string; scope: "account"; period: "day" | "week" | "month"; points: Array<{ timestamp: number; requests: number; tokens: number; spendUsd?: string }>; total: { requests: number; tokens: number; spendUsd?: string }; updatedAt?: number; state: ProviderAccountState; error?: string };
export type ProviderAccountAdapter = { id: string; matches(input: { providerId?: string; vendorKey?: string; baseUrl?: string }): boolean; getSnapshot(input: { providerId: string; baseUrl: string; apiKey: string }): Promise<ProviderAccountSnapshot>; getHistory?: (input: { providerId: string; baseUrl: string; apiKey: string; period: "day" | "week" | "month" }) => Promise<ProviderAccountHistory> };

function origin(baseUrl: string): string { return baseUrl.replace(/\/$/, ""); }
async function jsonFetch(url: string, apiKey: string): Promise<any> { const response = await fetch(url, { headers: { Authorization: `Bearer ${apiKey}`, Accept: "application/json" } }); if (!response.ok) throw new Error(`provider account request failed (${response.status})`); return response.json(); }
function matchesHost(input: { providerId?: string; vendorKey?: string; baseUrl?: string }, id: string, host: string): boolean { return [input.providerId, input.vendorKey].some((value) => String(value ?? "").toLowerCase().includes(id)) || String(input.baseUrl ?? "").toLowerCase().includes(host); }

export const providerAccountAdapters: ProviderAccountAdapter[] = [{
  id: "xkiro",
  matches: (input) => matchesHost(input, "xkiro", "xkiro.com"),
  async getSnapshot({ providerId, baseUrl, apiKey }) { try { const data = await jsonFetch(`${origin(baseUrl)}/usage`, apiKey); return { provider: providerId, scope: "account", state: "ready", updatedAt: Date.now(), staleAt: Date.now() + 60_000, plan: data.plan ?? null, wallet: data.wallet ? { balanceUsd: data.wallet.balance_usd, heldUsd: data.wallet.held_usd } : undefined, windows: Array.isArray(data.windows) ? data.windows.map((window: any) => ({ kind: window.kind, remainingUsd: window.remaining_usd, resetsInSec: window.resets_in_sec })) : [], freeTokens: data.free_tokens ? { usedToday: data.free_tokens.used_today, limitPerDay: data.free_tokens.limit_per_day, remaining: data.free_tokens.remaining } : undefined }; } catch { return { provider: providerId, scope: "account", state: "unavailable", error: "refresh_failed" }; } },
  async getHistory({ providerId, baseUrl, apiKey, period }) { try { const data = await jsonFetch(`${origin(baseUrl)}/usage/history?period=${period}`, apiKey); return { provider: providerId, scope: "account", period, state: "ready", updatedAt: Date.now(), points: (data.points ?? []).map((point: any) => ({ timestamp: Date.parse(point.ts), requests: point.requests ?? 0, tokens: point.tokens ?? 0, spendUsd: point.spend_usd })), total: { requests: data.total?.requests ?? 0, tokens: data.total?.tokens ?? 0, spendUsd: data.total?.spend_usd } }; } catch { return { provider: providerId, scope: "account", period, state: "unavailable", points: [], total: { requests: 0, tokens: 0 } }; } },
}, { id: "openrouter", matches: (input) => matchesHost(input, "openrouter", "openrouter.ai"), async getSnapshot({ providerId }) { return { provider: providerId, scope: "account", state: "unsupported", error: "management_key_required" }; } }, { id: "unsupported", matches: () => true, async getSnapshot({ providerId }) { return { provider: providerId, scope: "account", state: "unsupported", error: "provider_account_unavailable" }; } }];
